name: packo
description: Simplifying Flutter app build configurations. Tools for managing local packages.
version: 0.5.1
repository: https://github.com/nogipx/packo

executables:
  packo: packo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # CLI
  cli_util: ^0.4.1

  # Deploy
  process_run: ^0.14.1+3
  dotenv: ^4.2.0
  expressions: ^0.2.5
  yaml: ^3.1.1

  # Package
  pubspec_parse: ^1.2.1
  pub_semver: ^2.1.2

  # Runner
  args: ^2.4.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
