name: packo
description: Simplifying Flutter app build configurations. Tools for managing local packages.
version: 0.4.1
repository: https://github.com/nogipx/packo

executables:
  packo: packo

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  args: ^2.3.1
  dotenv: ^3.0.0
  process_run: ^0.12.3+2
  pubspec_parse: ^1.2.1
  pub_semver: ^2.1.2
  expressions: ^0.2.5
  cli_util: ^0.3.5
  yaml: ^3.1.1

dev_dependencies:
  lints: 1.0.1
  test: 1.21.4
